project:
  type: website
  output-dir: docs

website:
  title: "<b>Political Document Analysis Working Group (P-DAWG)</b><br><em><small><small>Department of Political Science, UW</small></small></em>"
  navbar:
    right:
      - index.qmd
      - schedule.qmd
      - literature.qmd
      - resources.qmd
      - about.qmd
      - icon: github
        href: https://github.com/uwpolgrads/PDAWG
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

