---
title: "About"
about:
  template: solana
  links:
    - icon: github
      text: Github
      href: https://github.com/uwpolgrads/PDAWG
---

Political Document Analysis Working Group (P-DAWG) is an initiative by graduate students at the Department of Political Science, University of Washington. We aim to foster discussion and knowledge exchange about the application of natural language processing (NLP) and relevant machine learning (ML) techniques to social sciences problems and data.

This website is a hub to centralize resources in a *collaborative and open sourced fashion*. All members have access to the Github repository. You can contribute by writing a blog post, adding items to the literature or useful resources pages, or signing up for presentation.

We invite presentations which usually fall within, but are not limited to, the following three styles:

-   *Code showcase:* Write up a reproducible script to introduce a technique (e.g., structural topic modeling), a R/Python package (e.g., transformers), or a workflow (How to pre-process text? How to run training/testing?)

-   *Latest development in the literature:* Summarize 1\~2 papers and present the latest advancements in how NLP techniques are being applied in social sciences. Lead a discussion in how we can incorporate those techniques in our field, and how they should be situated in the larger toolkit of NLP methods.

-   *Work in progress:* Circulate your work in progress that involves text as data. Present some preliminary descriptive statistics and dicuss your method of choice. Open up the floor for suggestions.

The working group is currently coordinated by Brian Leung (kpleung\[AT\]uw\[DOT\]edu), who can be contacted for any interest to join this group or inquiries.
